name:  AWS Tasks

on:
  push:
    branches:
      - main

env:
  AWS_DEFAULT_REGION: 'eu-west-1'
jobs:
  secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Retrieve Secrets
        id: secrets
        uses: t-botz/aws-secrets-manager-read-action@v2.0.0
        with:
          secret-id: dev/mam
          keys-as-env-vars: true

      - name: Use Secret
        run: |
          echo "$REACT_APP_SERVER_URL_PARAM"
          sed -i "s#%REACT_APP_SERVER_URL_PARAM%#$REACT_APP_SERVER_URL_PARAM#g" apprunner.yml

