# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
env:  
  Environment: ${{ (github.event_name == 'pull_request' && 'dev') || (contains(github.ref, 'develop') && 'qa') || (contains(github.ref, 'release') && 'staging') || (contains(github.ref, 'main') && 'prod') }}  
  PROJECT_NUMBER: ${{ (github.event_name == 'pull_request' && '797167706015') || (contains(github.ref, 'develop') && '797167706015') || (contains(github.ref, 'release') && '1084311286936') || (contains(github.ref, 'main') && '1081338543599') }}
  PROJECT_ID: ${{ (github.event_name == 'pull_request' && 'ajgc-dig-pdi-dev-mam-0.iam.gserviceaccount.com') || (contains(github.ref, 'develop') && 'ajgc-dig-pdi-dev-mam-0.iam.gserviceaccount.com') || (contains(github.ref, 'release') && 'ajgc-dig-pdi-vidicore-exp-0') || (contains(github.ref, 'main') && 'ajgc-dig-pdi-prd-mam-0') }}
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      WORKLOAD_IDENTITY_PROVIDER: "projects/${{ env.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-actions-prod-pool/providers/github-actions-provider"
      SERVICE_ACCOUNT: "mam-deploy-automation@${{ env.$PROJECT_ID }}"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!     

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo WORKLOAD_IDENTITY_PROVIDER ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          echo SERVICE_ACCOUNT ${{ env.SERVICE_ACCOUNT }}
